baseURL = "https://jogianotti.github.io/"
languageCode = "es-AR"
DefaultContentLanguage = "es"
title = "Sitio personal"
theme = "introduction"

[params]
    [[params.social]]
        url = "https://twitter.com/_jogianotti"
        icon = "twitter"
        icon_pack = "fab"
    [[params.social]]
        url = "https://linkedin.com/in/jogianotti"
        icon = "linkedin-in"
        icon_pack = "fab"
    [[params.social]]
        url = "https://github.com/jogianotti"
        icon = "github"
        icon_pack = "fab"
