baseURL = "https://jogianotti.github.io/"
defaultContentLanguage = "es"
theme = "introduction"

[languages]
    [languages.es]
        contentDir = "content/spanish"
        title = "Sitio personal"
        dateFormat = "2 de January de 2006"
    [languages.en]
        contentDir = "content/english"
        title = "Personal website"
        dateFormat = "January 2, 2006"

[params]
    [[params.social]]
        url = "https://twitter.com/_jogianotti"
        icon = "twitter"
        icon_pack = "fab"
    [[params.social]]
        url = "https://linkedin.com/in/jogianotti"
        icon = "linkedin-in"
        icon_pack = "fab"
    [[params.social]]
        url = "https://github.com/jogianotti"
        icon = "github"
        icon_pack = "fab"
